window.MATCHES = [
  {
    "matchNo": 1,
    "stage": "Group Stage",
    "team1": "Mexico",
    "team2": "South Africa",
    "team1Code": "A1",
    "team2Code": "A2",
    "date": "2026-06-12",
    "time": "01:00",
    "day": "Friday",
    "venue": "Mexico City",
    "status": "Not Started"
  },
  {
    "matchNo": 2,
    "stage": "Group Stage",
    "team1": "Rep. of Korea",
    "team2": "Czech Rep.",
    "team1Code": "A3",
    "team2Code": "A4",
    "date": "2026-06-12",
    "time": "08:00",
    "day": "Friday",
    "venue": "Guadalajara",
    "status": "Not Started"
  },
  {
    "matchNo": 3,
    "stage": "Group Stage",
    "team1": "Canada",
    "team2": "Bosnia/Herzeg.",
    "team1Code": "B1",
    "team2Code": "B2",
    "date": "2026-06-13",
    "time": "01:00",
    "day": "Saturday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 4,
    "stage": "Group Stage",
    "team1": "USA",
    "team2": "Paraguay",
    "team1Code": "D1",
    "team2Code": "D2",
    "date": "2026-06-13",
    "time": "07:00",
    "day": "Saturday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 8,
    "stage": "Group Stage",
    "team1": "Qatar",
    "team2": "Switzerland",
    "team1Code": "B3",
    "team2Code": "B4",
    "date": "2026-06-14",
    "time": "01:00",
    "day": "Sunday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 7,
    "stage": "Group Stage",
    "team1": "Brazil",
    "team2": "Morocco",
    "team1Code": "C1",
    "team2Code": "C2",
    "date": "2026-06-14",
    "time": "04:00",
    "day": "Sunday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 5,
    "stage": "Group Stage",
    "team1": "Haiti",
    "team2": "Scotland",
    "team1Code": "C3",
    "team2Code": "C4",
    "date": "2026-06-14",
    "time": "07:00",
    "day": "Sunday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 6,
    "stage": "Group Stage",
    "team1": "Australia",
    "team2": "Turkey",
    "team1Code": "D3",
    "team2Code": "D4",
    "date": "2026-06-14",
    "time": "10:00",
    "day": "Sunday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 10,
    "stage": "Group Stage",
    "team1": "Germany",
    "team2": "Curaçao",
    "team1Code": "E1",
    "team2Code": "E2",
    "date": "2026-06-14",
    "time": "23:00",
    "day": "Sunday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 11,
    "stage": "Group Stage",
    "team1": "Netherlands",
    "team2": "Japan",
    "team1Code": "F1",
    "team2Code": "F2",
    "date": "2026-06-15",
    "time": "02:00",
    "day": "Monday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 9,
    "stage": "Group Stage",
    "team1": "Ivory Coast",
    "team2": "Ecuador",
    "team1Code": "E3",
    "team2Code": "E4",
    "date": "2026-06-15",
    "time": "05:00",
    "day": "Monday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 12,
    "stage": "Group Stage",
    "team1": "Sweden",
    "team2": "Tunisia",
    "team1Code": "F3",
    "team2Code": "F4",
    "date": "2026-06-15",
    "time": "08:00",
    "day": "Monday",
    "venue": "Monterrey",
    "status": "Not Started"
  },
  {
    "matchNo": 14,
    "stage": "Group Stage",
    "team1": "Spain",
    "team2": "Cape Verde",
    "team1Code": "H1",
    "team2Code": "H2",
    "date": "2026-06-15",
    "time": "22:00",
    "day": "Monday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 16,
    "stage": "Group Stage",
    "team1": "Belgium",
    "team2": "Egypt",
    "team1Code": "G1",
    "team2Code": "G2",
    "date": "2026-06-16",
    "time": "01:00",
    "day": "Tuesday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 13,
    "stage": "Group Stage",
    "team1": "Saudi Arabia",
    "team2": "Uruguay",
    "team1Code": "H3",
    "team2Code": "H4",
    "date": "2026-06-16",
    "time": "04:00",
    "day": "Tuesday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 15,
    "stage": "Group Stage",
    "team1": "IR Iran",
    "team2": "New Zealand",
    "team1Code": "G3",
    "team2Code": "G4",
    "date": "2026-06-16",
    "time": "07:00",
    "day": "Tuesday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 17,
    "stage": "Group Stage",
    "team1": "France",
    "team2": "Senegal",
    "team1Code": "I1",
    "team2Code": "I2",
    "date": "2026-06-17",
    "time": "01:00",
    "day": "Wednesday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 18,
    "stage": "Group Stage",
    "team1": "Iraq",
    "team2": "Norway",
    "team1Code": "I3",
    "team2Code": "I4",
    "date": "2026-06-17",
    "time": "04:00",
    "day": "Wednesday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 19,
    "stage": "Group Stage",
    "team1": "Argentina",
    "team2": "Algeria",
    "team1Code": "J1",
    "team2Code": "J2",
    "date": "2026-06-17",
    "time": "07:00",
    "day": "Wednesday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 20,
    "stage": "Group Stage",
    "team1": "Austria",
    "team2": "Jordan",
    "team1Code": "J3",
    "team2Code": "J4",
    "date": "2026-06-17",
    "time": "10:00",
    "day": "Wednesday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 23,
    "stage": "Group Stage",
    "team1": "Portugal",
    "team2": "DR Congo",
    "team1Code": "K1",
    "team2Code": "K2",
    "date": "2026-06-17",
    "time": "23:00",
    "day": "Wednesday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 22,
    "stage": "Group Stage",
    "team1": "England",
    "team2": "Croatia",
    "team1Code": "L1",
    "team2Code": "L2",
    "date": "2026-06-18",
    "time": "02:00",
    "day": "Thursday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 21,
    "stage": "Group Stage",
    "team1": "Ghana",
    "team2": "Panama",
    "team1Code": "L3",
    "team2Code": "L4",
    "date": "2026-06-18",
    "time": "05:00",
    "day": "Thursday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 24,
    "stage": "Group Stage",
    "team1": "Uzbekistan",
    "team2": "Colombia",
    "team1Code": "K3",
    "team2Code": "K4",
    "date": "2026-06-18",
    "time": "08:00",
    "day": "Thursday",
    "venue": "Mexico City",
    "status": "Not Started"
  },
  {
    "matchNo": 25,
    "stage": "Group Stage",
    "team1": "Czech Rep.",
    "team2": "South Africa",
    "team1Code": "A4",
    "team2Code": "A2",
    "date": "2026-06-18",
    "time": "22:00",
    "day": "Thursday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 26,
    "stage": "Group Stage",
    "team1": "Switzerland",
    "team2": "Bosnia/Herzeg.",
    "team1Code": "B4",
    "team2Code": "B2",
    "date": "2026-06-19",
    "time": "01:00",
    "day": "Friday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 27,
    "stage": "Group Stage",
    "team1": "Canada",
    "team2": "Qatar",
    "team1Code": "B1",
    "team2Code": "B3",
    "date": "2026-06-19",
    "time": "04:00",
    "day": "Friday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 28,
    "stage": "Group Stage",
    "team1": "Mexico",
    "team2": "Rep. of Korea",
    "team1Code": "A1",
    "team2Code": "A3",
    "date": "2026-06-19",
    "time": "07:00",
    "day": "Friday",
    "venue": "Guadalajara",
    "status": "Not Started"
  },
  {
    "matchNo": 32,
    "stage": "Group Stage",
    "team1": "USA",
    "team2": "Australia",
    "team1Code": "D1",
    "team2Code": "D3",
    "date": "2026-06-20",
    "time": "01:00",
    "day": "Saturday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 30,
    "stage": "Group Stage",
    "team1": "Scotland",
    "team2": "Morocco",
    "team1Code": "C4",
    "team2Code": "C2",
    "date": "2026-06-20",
    "time": "04:00",
    "day": "Saturday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 29,
    "stage": "Group Stage",
    "team1": "Brazil",
    "team2": "Haiti",
    "team1Code": "C1",
    "team2Code": "C3",
    "date": "2026-06-20",
    "time": "06:30",
    "day": "Saturday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 31,
    "stage": "Group Stage",
    "team1": "Turkey",
    "team2": "Paraguay",
    "team1Code": "D4",
    "team2Code": "D2",
    "date": "2026-06-20",
    "time": "09:00",
    "day": "Saturday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 35,
    "stage": "Group Stage",
    "team1": "Netherlands",
    "team2": "Sweden",
    "team1Code": "F1",
    "team2Code": "F3",
    "date": "2026-06-20",
    "time": "23:00",
    "day": "Saturday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 33,
    "stage": "Group Stage",
    "team1": "Germany",
    "team2": "Ivory Coast",
    "team1Code": "E1",
    "team2Code": "E3",
    "date": "2026-06-21",
    "time": "02:00",
    "day": "Sunday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 34,
    "stage": "Group Stage",
    "team1": "Ecuador",
    "team2": "Curaçao",
    "team1Code": "E4",
    "team2Code": "E2",
    "date": "2026-06-21",
    "time": "06:00",
    "day": "Sunday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 36,
    "stage": "Group Stage",
    "team1": "Tunisia",
    "team2": "Japan",
    "team1Code": "F4",
    "team2Code": "F2",
    "date": "2026-06-21",
    "time": "10:00",
    "day": "Sunday",
    "venue": "Monterrey",
    "status": "Not Started"
  },
  {
    "matchNo": 38,
    "stage": "Group Stage",
    "team1": "Spain",
    "team2": "Saudi Arabia",
    "team1Code": "H1",
    "team2Code": "H3",
    "date": "2026-06-21",
    "time": "22:00",
    "day": "Sunday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 39,
    "stage": "Group Stage",
    "team1": "Belgium",
    "team2": "IR Iran",
    "team1Code": "G1",
    "team2Code": "G3",
    "date": "2026-06-22",
    "time": "01:00",
    "day": "Monday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 37,
    "stage": "Group Stage",
    "team1": "Uruguay",
    "team2": "Cape Verde",
    "team1Code": "H4",
    "team2Code": "H2",
    "date": "2026-06-22",
    "time": "04:00",
    "day": "Monday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 40,
    "stage": "Group Stage",
    "team1": "New Zealand",
    "team2": "Egypt",
    "team1Code": "G4",
    "team2Code": "G2",
    "date": "2026-06-22",
    "time": "07:00",
    "day": "Monday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 43,
    "stage": "Group Stage",
    "team1": "Argentina",
    "team2": "Austria",
    "team1Code": "J1",
    "team2Code": "J3",
    "date": "2026-06-22",
    "time": "23:00",
    "day": "Monday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 42,
    "stage": "Group Stage",
    "team1": "France",
    "team2": "Iraq",
    "team1Code": "I1",
    "team2Code": "I3",
    "date": "2026-06-23",
    "time": "03:00",
    "day": "Tuesday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 41,
    "stage": "Group Stage",
    "team1": "Norway",
    "team2": "Senegal",
    "team1Code": "I4",
    "team2Code": "I2",
    "date": "2026-06-23",
    "time": "06:00",
    "day": "Tuesday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 44,
    "stage": "Group Stage",
    "team1": "Jordan",
    "team2": "Algeria",
    "team1Code": "J4",
    "team2Code": "J2",
    "date": "2026-06-23",
    "time": "09:00",
    "day": "Tuesday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 47,
    "stage": "Group Stage",
    "team1": "Portugal",
    "team2": "Uzbekistan",
    "team1Code": "K1",
    "team2Code": "K3",
    "date": "2026-06-23",
    "time": "23:00",
    "day": "Tuesday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 45,
    "stage": "Group Stage",
    "team1": "England",
    "team2": "Ghana",
    "team1Code": "L1",
    "team2Code": "L3",
    "date": "2026-06-24",
    "time": "02:00",
    "day": "Wednesday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 46,
    "stage": "Group Stage",
    "team1": "Panama",
    "team2": "Croatia",
    "team1Code": "L4",
    "team2Code": "L2",
    "date": "2026-06-24",
    "time": "05:00",
    "day": "Wednesday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 48,
    "stage": "Group Stage",
    "team1": "Colombia",
    "team2": "DR Congo",
    "team1Code": "K4",
    "team2Code": "K2",
    "date": "2026-06-24",
    "time": "08:00",
    "day": "Wednesday",
    "venue": "Guadalajara",
    "status": "Not Started"
  },
  {
    "matchNo": 51,
    "stage": "Group Stage",
    "team1": "Switzerland",
    "team2": "Canada",
    "team1Code": "B4",
    "team2Code": "B1",
    "date": "2026-06-25",
    "time": "01:00",
    "day": "Thursday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 52,
    "stage": "Group Stage",
    "team1": "Bosnia/Herzeg.",
    "team2": "Qatar",
    "team1Code": "B2",
    "team2Code": "B3",
    "date": "2026-06-25",
    "time": "01:00",
    "day": "Thursday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 49,
    "stage": "Group Stage",
    "team1": "Scotland",
    "team2": "Brazil",
    "team1Code": "C4",
    "team2Code": "C1",
    "date": "2026-06-25",
    "time": "04:00",
    "day": "Thursday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 50,
    "stage": "Group Stage",
    "team1": "Morocco",
    "team2": "Haiti",
    "team1Code": "C2",
    "team2Code": "C3",
    "date": "2026-06-25",
    "time": "04:00",
    "day": "Thursday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 53,
    "stage": "Group Stage",
    "team1": "Czech Rep.",
    "team2": "Mexico",
    "team1Code": "A4",
    "team2Code": "A1",
    "date": "2026-06-25",
    "time": "07:00",
    "day": "Thursday",
    "venue": "Mexico City",
    "status": "Not Started"
  },
  {
    "matchNo": 54,
    "stage": "Group Stage",
    "team1": "South Africa",
    "team2": "Rep. of Korea",
    "team1Code": "A2",
    "team2Code": "A3",
    "date": "2026-06-25",
    "time": "07:00",
    "day": "Thursday",
    "venue": "Monterrey",
    "status": "Not Started"
  },
  {
    "matchNo": 55,
    "stage": "Group Stage",
    "team1": "Curaçao",
    "team2": "Ivory Coast",
    "team1Code": "E2",
    "team2Code": "E3",
    "date": "2026-06-26",
    "time": "02:00",
    "day": "Friday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 56,
    "stage": "Group Stage",
    "team1": "Ecuador",
    "team2": "Germany",
    "team1Code": "E4",
    "team2Code": "E1",
    "date": "2026-06-26",
    "time": "02:00",
    "day": "Friday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 57,
    "stage": "Group Stage",
    "team1": "Japan",
    "team2": "Sweden",
    "team1Code": "F2",
    "team2Code": "F3",
    "date": "2026-06-26",
    "time": "05:00",
    "day": "Friday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 58,
    "stage": "Group Stage",
    "team1": "Tunisia",
    "team2": "Netherlands",
    "team1Code": "F4",
    "team2Code": "F1",
    "date": "2026-06-26",
    "time": "05:00",
    "day": "Friday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 59,
    "stage": "Group Stage",
    "team1": "Turkey",
    "team2": "USA",
    "team1Code": "D4",
    "team2Code": "D1",
    "date": "2026-06-26",
    "time": "08:00",
    "day": "Friday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 60,
    "stage": "Group Stage",
    "team1": "Paraguay",
    "team2": "Australia",
    "team1Code": "D2",
    "team2Code": "D3",
    "date": "2026-06-26",
    "time": "08:00",
    "day": "Friday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 61,
    "stage": "Group Stage",
    "team1": "Norway",
    "team2": "France",
    "team1Code": "I4",
    "team2Code": "I1",
    "date": "2026-06-27",
    "time": "01:00",
    "day": "Saturday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 62,
    "stage": "Group Stage",
    "team1": "Senegal",
    "team2": "Iraq",
    "team1Code": "I2",
    "team2Code": "I3",
    "date": "2026-06-27",
    "time": "01:00",
    "day": "Saturday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 65,
    "stage": "Group Stage",
    "team1": "Cape Verde",
    "team2": "Saudi Arabia",
    "team1Code": "H2",
    "team2Code": "H3",
    "date": "2026-06-27",
    "time": "06:00",
    "day": "Saturday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 66,
    "stage": "Group Stage",
    "team1": "Uruguay",
    "team2": "Spain",
    "team1Code": "H4",
    "team2Code": "H1",
    "date": "2026-06-27",
    "time": "06:00",
    "day": "Saturday",
    "venue": "Guadalajara",
    "status": "Not Started"
  },
  {
    "matchNo": 63,
    "stage": "Group Stage",
    "team1": "Egypt",
    "team2": "IR Iran",
    "team1Code": "G2",
    "team2Code": "G3",
    "date": "2026-06-27",
    "time": "09:00",
    "day": "Saturday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 64,
    "stage": "Group Stage",
    "team1": "New Zealand",
    "team2": "Belgium",
    "team1Code": "G4",
    "team2Code": "G1",
    "date": "2026-06-27",
    "time": "09:00",
    "day": "Saturday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 67,
    "stage": "Group Stage",
    "team1": "Panama",
    "team2": "England",
    "team1Code": "L4",
    "team2Code": "L1",
    "date": "2026-06-28",
    "time": "03:00",
    "day": "Sunday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 68,
    "stage": "Group Stage",
    "team1": "Croatia",
    "team2": "Ghana",
    "team1Code": "L2",
    "team2Code": "L3",
    "date": "2026-06-28",
    "time": "03:00",
    "day": "Sunday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 71,
    "stage": "Group Stage",
    "team1": "Colombia",
    "team2": "Portugal",
    "team1Code": "K4",
    "team2Code": "K1",
    "date": "2026-06-28",
    "time": "05:30",
    "day": "Sunday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 72,
    "stage": "Group Stage",
    "team1": "DR Congo",
    "team2": "Uzbekistan",
    "team1Code": "K2",
    "team2Code": "K3",
    "date": "2026-06-28",
    "time": "05:30",
    "day": "Sunday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 69,
    "stage": "Group Stage",
    "team1": "Algeria",
    "team2": "Austria",
    "team1Code": "J2",
    "team2Code": "J3",
    "date": "2026-06-28",
    "time": "08:00",
    "day": "Sunday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 70,
    "stage": "Group Stage",
    "team1": "Jordan",
    "team2": "Argentina",
    "team1Code": "J4",
    "team2Code": "J1",
    "date": "2026-06-28",
    "time": "08:00",
    "day": "Sunday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 73,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "2A",
    "team2Code": "2B",
    "date": "2026-06-29",
    "time": "01:00",
    "day": "Monday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 76,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1C",
    "team2Code": "2F",
    "date": "2026-06-29",
    "time": "23:00",
    "day": "Monday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 74,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1E",
    "team2Code": "3-ABCDF",
    "date": "2026-06-30",
    "time": "02:30",
    "day": "Tuesday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 75,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1F",
    "team2Code": "2C",
    "date": "2026-06-30",
    "time": "07:00",
    "day": "Tuesday",
    "venue": "Monterrey",
    "status": "Not Started"
  },
  {
    "matchNo": 78,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "2E",
    "team2Code": "2I",
    "date": "2026-06-30",
    "time": "23:00",
    "day": "Tuesday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 77,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1I",
    "team2Code": "3-CDFGH",
    "date": "2026-07-01",
    "time": "03:00",
    "day": "Wednesday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 79,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1A",
    "team2Code": "3-CEFHI",
    "date": "2026-07-01",
    "time": "07:00",
    "day": "Wednesday",
    "venue": "Mexico City",
    "status": "Not Started"
  },
  {
    "matchNo": 80,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1L",
    "team2Code": "3-EHIJK",
    "date": "2026-07-01",
    "time": "22:00",
    "day": "Wednesday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 82,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1G",
    "team2Code": "3-AEHIJ",
    "date": "2026-07-02",
    "time": "02:00",
    "day": "Thursday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 81,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1D",
    "team2Code": "3-BEFIJ",
    "date": "2026-07-02",
    "time": "06:00",
    "day": "Thursday",
    "venue": "San Francisco Bay Area",
    "status": "Not Started"
  },
  {
    "matchNo": 84,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1H",
    "team2Code": "2J",
    "date": "2026-07-03",
    "time": "01:00",
    "day": "Friday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 83,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "2K",
    "team2Code": "2L",
    "date": "2026-07-03",
    "time": "05:00",
    "day": "Friday",
    "venue": "Toronto",
    "status": "Not Started"
  },
  {
    "matchNo": 85,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1B",
    "team2Code": "3-EFGIJ",
    "date": "2026-07-03",
    "time": "09:00",
    "day": "Friday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 88,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "2D",
    "team2Code": "2G",
    "date": "2026-07-04",
    "time": "00:00",
    "day": "Saturday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 86,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1J",
    "team2Code": "2H",
    "date": "2026-07-04",
    "time": "04:00",
    "day": "Saturday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 87,
    "stage": "Round of 32",
    "team1": "",
    "team2": "",
    "team1Code": "1K",
    "team2Code": "3-DEIJL",
    "date": "2026-07-04",
    "time": "07:30",
    "day": "Saturday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 90,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W73",
    "team2Code": "W75",
    "date": "2026-07-04",
    "time": "23:00",
    "day": "Saturday",
    "venue": "Houston",
    "status": "Not Started"
  },
  {
    "matchNo": 89,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W74",
    "team2Code": "W77",
    "date": "2026-07-05",
    "time": "03:00",
    "day": "Sunday",
    "venue": "Philadelphia",
    "status": "Not Started"
  },
  {
    "matchNo": 91,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W76",
    "team2Code": "W78",
    "date": "2026-07-06",
    "time": "02:00",
    "day": "Monday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  },
  {
    "matchNo": 92,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W79",
    "team2Code": "W80",
    "date": "2026-07-06",
    "time": "06:00",
    "day": "Monday",
    "venue": "Mexico City",
    "status": "Not Started"
  },
  {
    "matchNo": 93,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W83",
    "team2Code": "W84",
    "date": "2026-07-07",
    "time": "01:00",
    "day": "Tuesday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 94,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W81",
    "team2Code": "W82",
    "date": "2026-07-07",
    "time": "06:00",
    "day": "Tuesday",
    "venue": "Seattle",
    "status": "Not Started"
  },
  {
    "matchNo": 95,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W86",
    "team2Code": "W88",
    "date": "2026-07-07",
    "time": "22:00",
    "day": "Tuesday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 96,
    "stage": "Round of 16",
    "team1": "",
    "team2": "",
    "team1Code": "W85",
    "team2Code": "W87",
    "date": "2026-07-08",
    "time": "02:00",
    "day": "Wednesday",
    "venue": "Vancouver",
    "status": "Not Started"
  },
  {
    "matchNo": 97,
    "stage": "Quarter-final",
    "team1": "",
    "team2": "",
    "team1Code": "W89",
    "team2Code": "W90",
    "date": "2026-07-10",
    "time": "02:00",
    "day": "Friday",
    "venue": "Boston",
    "status": "Not Started"
  },
  {
    "matchNo": 98,
    "stage": "Quarter-final",
    "team1": "",
    "team2": "",
    "team1Code": "W93",
    "team2Code": "W94",
    "date": "2026-07-11",
    "time": "01:00",
    "day": "Saturday",
    "venue": "Los Angeles",
    "status": "Not Started"
  },
  {
    "matchNo": 99,
    "stage": "Quarter-final",
    "team1": "",
    "team2": "",
    "team1Code": "W91",
    "team2Code": "W92",
    "date": "2026-07-12",
    "time": "03:00",
    "day": "Sunday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 100,
    "stage": "Quarter-final",
    "team1": "",
    "team2": "",
    "team1Code": "W95",
    "team2Code": "W96",
    "date": "2026-07-12",
    "time": "07:00",
    "day": "Sunday",
    "venue": "Kansas City",
    "status": "Not Started"
  },
  {
    "matchNo": 101,
    "stage": "Semi-final",
    "team1": "",
    "team2": "",
    "team1Code": "W97",
    "team2Code": "W98",
    "date": "2026-07-15",
    "time": "01:00",
    "day": "Wednesday",
    "venue": "Dallas",
    "status": "Not Started"
  },
  {
    "matchNo": 102,
    "stage": "Semi-final",
    "team1": "",
    "team2": "",
    "team1Code": "W99",
    "team2Code": "W100",
    "date": "2026-07-16",
    "time": "01:00",
    "day": "Thursday",
    "venue": "Atlanta",
    "status": "Not Started"
  },
  {
    "matchNo": 103,
    "stage": "Third-place match",
    "team1": "",
    "team2": "",
    "team1Code": "RU101",
    "team2Code": "RU102",
    "date": "2026-07-19",
    "time": "03:00",
    "day": "Sunday",
    "venue": "Miami",
    "status": "Not Started"
  },
  {
    "matchNo": 104,
    "stage": "Final",
    "team1": "",
    "team2": "",
    "team1Code": "W101",
    "team2Code": "W102",
    "date": "2026-07-20",
    "time": "01:00",
    "day": "Monday",
    "venue": "New York/New Jersey",
    "status": "Not Started"
  }
];
